---
- name: DevOps Assessment Playbook
  hosts: targets
  become: yes
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - role: ca_certs
    - role: deploy_app
  tasks:
    - name: Install Python 3 and venv
      apt:
        name:
          - python3
          - python3-venv
        state: present
      become: yes
  handlers:
    - name: restart-example-service
      systemd:
        name: example.service
        state: restarted
